name             'activelamp_composer'
maintainer       'Bez Hermoso, ActiveLAMP'
maintainer_email 'bez@activelamp.com'
license          'Apache 2.0'
description      'Provides the `composer` resource.'
long_description 'Provides the `composer` resource that can interact with Composer projects.'
version          '0.0.1'
