name 'sonarqube-mysql'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
license 'MIT'
description 'Configures a MySQL database for use with SonarQube'
long_description 'Configures a MySQL database for use with SonarQube'
version '0.1.1'
supports 'ubuntu'
supports 'centos'
depends 'database'
depends 'mysql2_chef_gem'
